@startuml C4_Context_Diagram
set separator none
title Контекст системы "Умный дом" в PropDevelopment

top to bottom direction

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include <C4/C4_Container>

Person(Собственник, "Собственник жилья", "Пользуется мобильным приложением для управления умным домом")
Person(Жилец, "Жилец", "Получает доступ через домофон/шлагбаум")
System(МобильноеПриложение, "Мобильное приложение PropDevelopment", "Существующее приложение для собственников")
System(ПартнёрУмныйДом, "Платформа партнёра", "Предоставляет сервисы: домофон + шлагбаум")
System(SmartBarrier, "Система шлагдбаума", "")
System(SmartIntercom, "Система домофона", "")

Rel(Собственник, МобильноеПриложение, "Управляет доступом: добавляет лица/номера")
Rel(Жилец, ПартнёрУмныйДом, "Взаимодействует с домофоном/шлагбаумом")
Rel(МобильноеПриложение, SmartBarrier, "Синхронизирует данные собственников (REST)")
Rel(МобильноеПриложение, SmartIntercom, "Синхронизирует данные собственников (REST)")
Rel(ПартнёрУмныйДом, SmartBarrier, "Передаёт события доступа (например, попытка проезда)")
Rel(ПартнёрУмныйДом, SmartIntercom, "Передаёт события доступа (например, попытка входа)")
@enduml